[tool.black]
# Compatible with the flake8 line length
line-length = 120

[tool.ruff]
line-length = 120
# https://beta.ruff.rs/docs/rules/
select = [
    "E",  # pycodestyle
    "F", "W",  # Pyflakes
    "I",  # isort
    "N",  # pep8-naming
    "D",  # pydocstyle
    "UP",  # pyupgrade
    "S",  # flake8-bandit
    "BLE",  # flake8-blind-except
    "FBT",  # flake8-boolean-trap
    "B",  # flake8-bugbear
    "A",  # flake8-builtins
    "COM",  # flake8-commas
    "C4",  # flake8-comprehensions
    "DJ",  # flake8-django
    "ISC",  # flake8-implicit-str-concat
    "INP",  # flake8-no-pep420
    "PIE",  # flake8-pie
    "PT",  # flake8-pytest-style
    "Q",  # flake8-quotes
    "RSE",  # flake8-raise
    "RET",  # flake8-return
    "SIM",  # flake8-simplify
    "TCH",  # flake8-type-checking
    "PTH",  # flake8-use-pathlib
    "PL", "PLC", "PLE", "PLR", "PLW",  # Pylint
    "TRY",  # tryceratops
]
ignore = [
    "D203",  # in conflict with D211
    "D212",  # in conflict with D213
    "TRY003",  # ignore long messages for errors
]
extend-exclude = [
    "*/migrations/*"
]

[tool.ruff.per-file-ignores]
"tests/*" = ["S101"]
"scripts/*" = ["INP001"]
"docker/app/gunicorn.conf.py" = ["INP001"]
"__init__.py" = ["F401"]

[tool.ruff.pydocstyle]
convention = "google"
