global:
  scrape_interval: "1m"
  scrape_timeout: "10s"
  evaluation_interval: "1m"

scrape_configs:
  - job_name: prometheus
    metrics_path: /prometheus/metrics
    tls_config:
      insecure_skip_verify: true
    static_configs:
      - targets:
          - "nginx:80"
